import { fetchLiveIssues, isTrulyOpenIssue } from "../../artifacts/api-server/src/lib/drips-client";
import { generateAiProposal } from "../../artifacts/api-server/src/lib/proposal-generator";

async function main() {
  console.log("=== Testing DripWave Live Issue Fetch & Strict Filtering ===");
  const issues = await fetchLiveIssues();
  console.log(`Fetched ${issues.length} live issues from Drips API.`);

  const openIssues = issues.filter(isTrulyOpenIssue);
  console.log(`Found ${openIssues.length} truly unassigned, open issues.`);

  if (openIssues.length > 0) {
    const sample = openIssues[0];
    console.log("\nSample Open Issue:");
    console.log(`- Title: ${sample.title}`);
    console.log(`- Repo: ${sample.repo?.gitHubRepoFullName || sample.repo?.gitHubRepoName}`);
    console.log(`- Points: ${sample.points || 100}`);
    console.log(`- Assigned: ${sample.assignedApplicant ? JSON.stringify(sample.assignedApplicant) : "None (Truly Open)"}`);
    console.log(`- Assignees: ${sample.assignees?.length || 0}`);

    console.log("\n=== Testing AI Proposal Pitch Generation ===");
    const proposalRes = await generateAiProposal({
      issueTitle: sample.title,
      issueSummary: sample.body || sample.title,
      repository: sample.repo?.gitHubRepoFullName || "stellar/stellar-sdk",
      points: sample.points || 100,
      skills: ["TypeScript", "Rust", "Soroban", "testing"],
      bio: "Senior full-stack engineer and Soroban smart contract builder.",
    });

    console.log(`Generated by: ${proposalRes.provider}`);
    console.log("Proposal Output:");
    console.log("-----------------------------------------");
    console.log(proposalRes.proposal);
    console.log("-----------------------------------------");
  }

  console.log("\n✓ DripWave Engine Verification Passed!");
}

main().catch(console.error);
